# Generated by Django 3.2.10 on 2022-04-09 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dtail', '0002_auto_20220406_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('code', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MS', 'MID SEMESTER'), ('ES', 'END SEMESTER'), ('IM', 'INTERMEDIATE')], max_length=2)),
                ('date', models.DateField()),
                ('marks', models.IntegerField()),
                ('semester', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')])),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_branch', to='Dtail.branch')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='Examination.subject')),
            ],
        ),
    ]
