# Generated by Django 3.2.10 on 2022-04-10 20:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Dtail', '0002_auto_20220406_2059'),
        ('Examination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswersheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('answersheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examination.answersheet')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examination.exam')),
                ('invigilator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dtail.professor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dtail.student')),
            ],
        ),
    ]
